### ISSUE TITLE
Builds Fail on GitHub Actions (actions-rs/cargo) for x86_64-unknown-linux-musl Target

### ISSUE THREAD

**Issue by naftulikay** [sfackler/rust-openssl#1577]
### Background

I am using the [`actions-rs`](https://github.com/actions-rs) GitHub Actions, [`actions-rs/toolchain@v1`](https://github.com/actions-rs/toolchain) and [`actions-rs/cargo@v1`](https://github.com/actions-rs/cargo), and I'm building for `x86_64-unknown-linux-musl`. 

### Workflow File

My workflow looks like this:

```yaml
---
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

env:
  CACHE_VERSION: v1
  DEV_PACKAGES: build-essential musl musl-dev musl-tools libssl-dev linux-musl-dev pkg-config

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install system build dependencies
        run: sudo apt-get update && sudo apt-get install ${DEV_PACKAGES}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-rust-build-${{ env.CACHE_VERSION }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-rust-build-${{ env.CACHE_VERSION }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl # build static binaries
      # cargo build --release
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
```

### Build Environment

In short:
 1. Host architecture is always `x86_64`.
 1. I am running on `ubuntu-latest`, which I assume is `focal`/`20.04`
 1. My local dev machine is `bionic`/`18.04`.
 1. My target is `x86_64-unknown-linux-musl`
 1. I'm on `stable`, so `1.57.0`.
 1. I am always installing `build-essential`, `musl`, `musl-dev`, `musl-tools`, `libssl-dev`, `linux-musl-dev`, `pkg-config`
 1. I am essentially executing `cargo build --release --target x86_64-unknown-linux-musl`
 
 The `openssl-sys` crate being used is `0.9.71`, which appears to be fairly recent.

### Error Log
 
 The error log looks like this:

```text
Error: failed to run custom build command for `openssl-sys v0.9.71`
Caused by:
  process didn't exit successfully: `/home/runner/work/my-project/my-project/target/release/build/openssl-sys-37a921daded85d66/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "pkg-config has not been configured to support cross-compilation.\n\nInstall a sysroot for the target platform and configure it via\nPKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\ncross-compiling wrapper for pkg-config and set it via\nPKG_CONFIG environment variable."

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-musl
  openssl-sys = 0.9.71

  ', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.71/build/find_normal.rs:180:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Summary

`openssl-sys` can't find the OpenSSL headers on Ubuntu 20.04 amd64 in GitHub Actions when building on stable Rust with `libssl-dev` installed.

I'm going to try to set the `OPENSSL_DIR` environment variable and see if that gets me anywhere, but I'm not sure what the problem might be. I'm installing `pkg-config`, so it should be able to locate `libssl` headers, maybe I'll also try `ldconfig` or something, but I don't know if that's related.
