### ISSUE TITLE
environments variables are not set for cross compiling 

### ISSUE THREAD

**Issue by Ludea** [sfackler/rust-openssl#1682]
Hi, 

I set env var (On Windows) `TARGET_CC`,  `CC_aarch64-linux-android` to` C:/hostedtoolcache/windows/ndk/r25b/x64/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe` but into log I get :
```
  CC_aarch64-linux-android = None
  CC_aarch64_linux_android = None
  TARGET_CC = Some("C:/hostedtoolcache/windows/ndk/r25b/x64/toolchains/llvm/prebuilt/windows-x86_64\\bin\\aarch64-linux-android24-clang.cmd")
```

Openssl seems to not reading my env var.
I set twice the env var, by package.json (https://github.com/Ludea/tauri-mobile/blob/main/package.json#L10) (I run `tauri android build` command, it build all dependencies, and so openssl/openssl-sys) and by GHA (https://github.com/Ludea/tauri-mobile/blob/main/.github/workflows/build.yml#L120)

So I can't build the openssl-sys, cygwin doesnt read Windows path (double `\\`).
`   /usr/bin/sh: C:/hostedtoolcache/windows/ndk/r25b/x64/toolchains/llvm/prebuilt/windows-x86_64binclang.exe: No such file or directory`

**Comment by sfackler** [comment]
I'm not familiar with tauri - something is presumably blocking the environment variable before it hits the build script.

**Comment by Ludea** [comment]
I think it's not reaaly an issue with tauri.

I use GHA like: 
```
      run: yarn tauri android build
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        TARGET_CC: C:/hostedtoolcache/windows/ndk/r25b/x64/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
```
I can see the `NDK_HOME` env var (unless the build fail) but not TARGET_CC. 
https://github.com/Ludea/tauri-mobile/runs/8268371893?check_suite_focus=true#step:13:266
