### ISSUE TITLE
could not find system library 'openssl' required by the 'openssl-sys' - Github Actions

### ISSUE THREAD

**Issue by iustin24** [sfackler/rust-openssl#1686]
Hi,

I am encountering the following issue when trying to build using github actions:

```
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\nerror: could not find system library 'openssl' required by the 'openssl-sys' crate\n\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'openssl' found\n"
```

This is what my yml file contains:
```yml
      - name: Install System Dependencies
        run: |
          export OPENSSL_DIR=/usr/lib/ssl
          env
          sudo apt-get update
          sudo apt-get install -y openssl libssl-dev pkg-config gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        env:
          PKG_CONFIG_PATH: ${{ matrix.pkg_config_path }}
          OPENSSL_DIR: /usr/lib/ssl
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
```
My Cargo.toml also has the following line:
```toml
openssl = { version = "0.10.41", features = ["vendored"] }
```

My yml file:

https://github.com/iustin24/chameleon/blob/master/.github/workflows/rust.yml
