### ISSUE TITLE
Cross compile from Linux to Windows using vendored feature fails due to incompatible perl version

### ISSUE THREAD

**Issue by blacktemplar** [sfackler/rust-openssl#2308]
I am trying to cross compile a project depending on openssl with the vendored feature. My host machine is running Linux and I have perl installed, but when I run `cargo build --release --target=x86_64-pc-windows-msvc` I get the following error:

```
******************************************************************************
  This perl implementation doesn't produce Windows like paths (with backward
  slash directory separators).  Please use an implementation that matches your
  building platform.

  This Perl version: 5.40.0 for x86_64-linux-thread-multi
  ******************************************************************************
  thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.3.2+3.3.2/src/lib.rs:633:9:
```

I was surprised that I didn't find any discussions/issues about this and that there is nothing mentioned in the docs. How can I fix this, does this mean cross compilation does not really work for the vendored feature? Or do I need a different perl?

**Comment by SheldonNico** [comment]
I think original openssl build script doesn't support cross compiling for msvc([issue 1470](https://github.com/rust-lang/rustup/issues/1470#issuecomment-408622305)), maybe gnu can work. But I managed to cross a `hello_word` for `x86_64-pc-windows-msvc` on linux by using [cross-rs](https://github.com/cross-rs/cross). For anyone want try:

1. follow [cross-toolchains](https://github.com/cross-rs/cross-toolchains) to build `x86_64-pc-windows-msvc-cross` image
2. Modify `Cargo.toml`
```toml
[dependencies]
openssl = { version = "0.10.73", features = ["vendored"] }
# openssl = { version = "0.10.73" }

[workspace.metadata.cross.target.x86_64-pc-windows-msvc]
image = "ghcr.io/cross-rs/x86_64-pc-windows-msvc-cross:local"
```
3. Change perl location in `Cargo.toml`(It will use system perl by default, which will warn `Windows like paths`)
```toml
[workspace.metadata.cross.target.x86_64-pc-windows-msvc.env]
passthrough = [
    "OPENSSL_SRC_PERL=/opt/bin/perl.exe", # fix for openssl cross compiling
]

```
