### ISSUE TITLE
Build failed on travis-ci linux 

### ISSUE THREAD

**Issue by Folyd** [sfackler/rust-openssl#977]
I got a build error on travis-ci, here is the error log.

```
error: failed to run custom build command for `openssl-sys v0.9.35`
process didn't exit successfully: `/home/travis/build/anyshortcut/anyshortcut-cli/target/debug/build/openssl-sys-a968de524628928a/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"
--- stderr
thread 'main' panicked at '
Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.
Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.
    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-musl
    openssl-sys = 0.9.35
', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.35/build/main.rs:265:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

and here are my [.travis.yml](https://github.com/anyshortcut/anyshortcut-cli/blob/563296231c2115a52ccbd31792a3de479aa4be5d/.travis.yml) file:
```yml
dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
  # Default target on travis-ci.
  # Used as conditional check in the install stage
  - HOST=x86_64-unknown-linux-gnu
  - CRATE_NAME=anyshortcut-cli

matrix:
  include:
  # Linux
  - env: TARGET=i686-unknown-linux-gnu
  - env: TARGET=i686-unknown-linux-musl
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-unknown-linux-musl

  # OSX
  - env: TARGET=x86_64-apple-darwin
    os: osx

addons:
  apt:
    packages:
    - pkg-config
    - libssl-dev
    # needed for i686-unknown-linux-gnu target
    - gcc-multilib
    # needed for musl targets
    - musl-tools
    # needed to build deb packages
    - fakeroot

before_install:
- set -e
- rustup self update

install:
# prevent target re-add error from rustup
- if [[ $TRAVIS_OS_NAME = linux && $HOST != $TARGET ]]; then rustup target add $TARGET; fi

script:
# Incorporate TARGET env var to the build and test process
- cargo build --target $TARGET --verbose
- cargo test --target $TARGET --verbose

after_script: set +e

before_deploy:
- cargo build --target "$TARGET" --release --verbose

deploy:
  api_key:
    secure: jS0oZYqAlGzrisNWiJW24JdxuALiNo9VuPRYcAiT5qQ6HH8wne/sFC5zWLq5HZmPVtnBUTXPGV3dfj0jYWADFIKW4Rhgu1nPShVhOEa3wmwptPaxiOZWgoV1yXvONYJmYRiI/Dko0tBGPJ/PDv6MuFPLFPlJXbeS8KDth5Am/8kSbGsoePpIGwhK7gadb2GCkfHTNX3rvzzUt8nYp3G7wNj6YCJL3YIu91OaYAAoWjOZZ/bwwreJKXEkeKfReUYPJfUJXzJXbsPZ0nFv2zljTMynE956JZOS1lBN59BIh8AeNvy4prng0YQSQdM/G9oOBBUQ7HfQhJRcWCUoTjjnP8iao9t2rCibsQ8xORaz5lQfW2n/VKV1DH/grveUG2fwjNirfm6VIRpCtfE1gdWCEMcG8xyUKNXdwiZRqJtoRulBFesrarJWXJjX0xsjDEimYNRinSYdrmPyXYIbqNVsNzUUD8ne7HCEZoYCyTWtl9q587mFr7PlLGUU62/syWiIqw3cttpY7jSbRIwEX7fedqXLQCTpF1q9e/KRD/zCAvRsUQ7Z4SgS0Xlnf/2GFElFhNy/LyCvqGbVoE3Nl0KJavkAUixyhuU3OkqDVzUSsMHRK9eOuW46r58AgA1erDoaaNV9rklnS+dtgNjO59ENq7e0El3+exuDvjqPm9PcXYY=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

branches:
  only:
  # release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

notifications:
  email:
    on_success: never

```

I have add **libssl-dev** into `addons`, but still get the error.

Here is the travis [build history](https://travis-ci.com/anyshortcut/anyshortcut-cli/builds/82230954).
